name: Run Scheduled Tests Hourly

on:
  schedule:
    # Cron expression for every Monday at midnight UTC
    - cron: "0 * * * *"
  workflow_dispatch:  # Allow manual trigger from the Actions tab

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"
      - name: RDC Native App Android
        run: mvn test -pl appium/appium-app/appium-app-examples -Dtest=AndroidNativeAppTest -Dregion=eu
      - name: RDC Native App IOS
        run: mvn test -pl appium/appium-app/appium-app-examples  -Dtest=IOSNativeAppTest -Dregion=eu
