name: Run Scheduled Tests Every Monday

on:
  schedule:
    # Cron expression for every Monday at midnight UTC
    - cron: "0 * * * *"
  workflow_dispatch:  # Allow manual trigger from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest # You can choose macos-latest or ubuntu-latest

    steps:
      - name: Set up Sauce Labs credentials from secrets
        run: |
          echo "SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }}" >> $GITHUB_ENV
      - name: Run tests using the script
        run: |
          mvn clean test -pl appium -Dtest=AndroidNativeAppTest -Dregion=us ; mvn clean test -pl appium -Dtest=IOSNativeAppTest -Dregion=us
